language: android
jdk: oraclejdk7

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-21.1.1

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17

before_install:
 - chmod +x gradlew

script:
  # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew build

deploy:
  provider: releases
  api-key: "9deb0e36f005b5d0aa608eb8a18a66d152aded75 "
  file: "./app/build/outputs/apk/app-debug.apk"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper